#input
type = input("encrypt or decrypt?: ")
pass_key = input(f"enter the key to {type} (letters only): ")

#encryption/decryption
pass_key = pass_key.lower()

if type == "encrypt":
    pass_key = pass_key.replace("a" , "b")
    pass_key = pass_key.replace("b" , "c")
    pass_key = pass_key.replace("c" , "d")
    pass_key = pass_key.replace("d" , "e")
    pass_key = pass_key.replace("e" , "f")
    pass_key = pass_key.replace("f" , "g")
    pass_key = pass_key.replace("g" , "h")
    pass_key = pass_key.replace("h" , "i")
    pass_key = pass_key.replace("i" , "j")
    pass_key = pass_key.replace("j" , "k")
    pass_key = pass_key.replace("k" , "l")
    pass_key = pass_key.replace("l" , "m")
    pass_key = pass_key.replace("m" , "n")
    pass_key = pass_key.replace("n" , "o")
    pass_key = pass_key.replace("o" , "p")
    pass_key = pass_key.replace("p" , "q")
    pass_key = pass_key.replace("q" , "r")
    pass_key = pass_key.replace("r" , "s")
    pass_key = pass_key.replace("s" , "t")
    pass_key = pass_key.replace("t" , "u")
    pass_key = pass_key.replace("u" , "v")
    pass_key = pass_key.replace("v" , "w")
    pass_key = pass_key.replace("w" , "x")
    pass_key = pass_key.replace("x" , "y")
    pass_key = pass_key.replace("y" , "z")
    pass_key = pass_key.replace("z" , "a")
    encrypted_key = pass_key[::-1]
    print(f"encrypted key: {encrypted_key}")

elif type == "decrypt":
    pass_key = pass_key.replace("a" , "z")
    pass_key = pass_key.replace("b" , "a")
    pass_key = pass_key.replace("c" , "b")
    pass_key = pass_key.replace("d" , "c")
    pass_key = pass_key.replace("e" , "d")
    pass_key = pass_key.replace("f" , "e")
    pass_key = pass_key.replace("g" , "f")
    pass_key = pass_key.replace("h" , "g")
    pass_key = pass_key.replace("i" , "h")
    pass_key = pass_key.replace("j" , "i")
    pass_key = pass_key.replace("k" , "j")
    pass_key = pass_key.replace("l" , "k")
    pass_key = pass_key.replace("m" , "l")
    pass_key = pass_key.replace("n" , "m")
    pass_key = pass_key.replace("o" , "n")
    pass_key = pass_key.replace("p" , "o")
    pass_key = pass_key.replace("q" , "p")
    pass_key = pass_key.replace("r" , "q")
    pass_key = pass_key.replace("s" , "r")
    pass_key = pass_key.replace("t" , "s")
    pass_key = pass_key.replace("u" , "t")
    pass_key = pass_key.replace("v" , "u")
    pass_key = pass_key.replace("w" , "v")
    pass_key = pass_key.replace("x" , "w")
    pass_key = pass_key.replace("y" , "x")
    pass_key = pass_key.replace("z" , "y")
    decrypted_key = pass_key[::-1]
    print(f"decrypted key: {decrypted_key}")

else:
    print("can only encrypt or decrypt key")